[project]
name = "sim-to-excel"
version = "1.0.5"
requires-python = ">=3.11"
dependencies = [
    "xlsxwriter>=3.2.9",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
